HotDogStand: HotDogStand.o HotDogStandTest.o
		g++ -o HotDogStand HotDogStand.o HotDogStandTest.o

HotDogStand.o: HotDogStand.cpp
		g++ -c HotDogStand.cpp

HotDogStandTest.o: HotDogStandTest.cpp
		g++ -c HotDogStandTest.cpp

clean: 
	rm HotDogStand *.o
